### PR TITLE
fix: Linux: no connection to localhost:3233 (closes #87)

### LINKED ISSUE #87: Linux: no connection to localhost:3233
Do you provide support for Linux?

In the following setup:

- Fresh Debian 10 installed
- AIO-CLT installed
- Docker installed
- App generated with a "generic" action.

there is an issue:

The application is not available when trying to start using `aio app run --local`
A timeout is given.

I tried the following:

Docker's network interface is `docker0` with IP `172.17.0.1`

```
3: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:99:4a:ab:f8 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
```

I changed this file manually:

`/home/marko/.nvm/versions/node/v12.14.1/lib/node_modules/@adobe/aio-cli/node_modules/@adobe/aio-app-scripts/scripts/dev.js`

`const OW_LOCAL_APIHOST = 'http://172.17.0.1:3233'`

This is working now.

I also tried to put 

`AIO_RUNTIME_APIHOST=http://172.17.0.1:3233`

to `.env` before starting using `aio app run --local`. But this didn't work

### PR DESCRIPTION
**Pull request by shazron**
## Description

See #87
Exposes OW_LOCAL_* environment variables for overriding the defaults set in the scripts.

This has minimal impact on the existing `dev` script, the OW_LOCAL_* variables are `require`d from an external file.

## How Has This Been Tested?

npm test
manual test `aio app run --local`

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by shazron** [comment]
Windows is complaining about two lines not being covered, while Linux and macOS report 100% 🤷‍♂

**Comment by moritzraho** [comment]
> Windows is complaining about two lines not being covered, while Linux and macOS report 100% 🤷‍♂

could it be that JSON.parse here https://github.com/adobe/aio-app-scripts/pull/88/files#diff-48f4b65a539f065afc50caf0c312d0e1R11 is failing?

**Comment by shazron** [comment]
@moritzraho looks like it, i'm adding a specific test file for that new file I created so as to be absolutely sure

**Comment by moritzraho** [comment]
ok great !

**Comment by shazron** [comment]
Unfortunately I have encountered a problem on macOS: you can't route to the bridge IP address (it can't be bound) and is a known issue: https://forums.docker.com/t/host-excluded-from-bridge-network/12015/2 

I'm not sure if this is the same on Windows - I will test that next. So, we need to "special case" this it seems, depending on the results of the Windows manual test.

**Comment by shazron** [comment]
I can't run Docker on Windows under Parallels Mac, nested virtualizations are not supported for Docker (it may or may not run), and I don't have a Windows PC. But based on the Known Issues for the latest Docker Desktop for Windows https://docs.docker.com/docker-for-windows/#docker-desktop-community-2203 it seems that the direct IP address  communication from host to container has been removed in this version.

So based on this information, I think we will just have to special case for Linux via inspecting `process.platform` (if it's `win32` or `darwin`(macOS) use localhost, if it's neither, use the gateway IP address).

**Comment by moritzraho** [comment]
@shazron sorry for the late reply, good catch, yeah in windows and mac the docker container runs in a vm.
I have a VM set up with Windows, nested virtualization and docker for windows, running the `run --local` command works.
I tried running the `docker inspect bridge` command and there is no Gateway it seems
```
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.17.0.0/16"
                }
            ]
        },

```

**Comment by moritzraho** [comment]
process.platform can take those values
```
    aix
    darwin
    freebsd
    linux
    openbsd
    sunos
    win32
```
I think we can check if === linux then take the bridge ip otherwise go to linux

**Comment by shazron** [comment]
@moritzraho i think special casing it for win32 and darwin is the way to go, the other *nixes do not have this limitation, so we shouldn't restrict it to just `linux`

**Comment by shazron** [comment]
@moritzraho I've re-tested my latest changes on Mac and Ubuntu Linux, everything works as expected. Can you re-test the changes on Windows to verify?

**Comment by shazron** [comment]
Turns out I need Parallels for Mac, Pro Edition to get nested virtualization working. Managed to get Docker for Windows running on that, and tested the changes, they work well on Windows 10. Merging.

**Pull request merged**
